### ISSUE TITLE
ValueError: Invalid TPUconfig `eval_training_input_configuration` value. SLICED mode only works on use_tpu=True

### ISSUE THREAD

**Issue by slacklife** [google-research/simclr#13]
I want to reproduce the experiment on cifar10 and use the command [here](https://github.com/google-research/simclr/#finetuning) with the flag "--use_tpu=False".
I got the error that is "ValueError: Invalid TPUconfig `eval_training_input_configuration` value. SLICED mode only works on use_tpu=True".
The is config SLICED mode is [here](https://github.com/google-research/simclr/blob/master/run.py#L369)
Is this a problem for others?
I use the tf1.15 same as [here](https://github.com/google-research/simclr/blob/master/requirements.txt)

**Comment by chentingpc** [comment]
This is a bug and will be fixed soon. For now, there's an easy way to get around it, se https://github.com/google-research/simclr/issues/11#issuecomment-600289389.

**Comment by chentingpc** [comment]
FYI, this is now fixed (in https://github.com/google-research/simclr/commit/f3ca72f7efc085ad4abdb65f7a63459d9cfda78f).

**Comment by Ivy-C-85** [comment]
> FYI, this is now fixed (in [f3ca72f](https://github.com/google-research/simclr/commit/f3ca72f7efc085ad4abdb65f7a63459d9cfda78f)).

I still have this problem when I use Colab to run tensorflow 1.15.2

**Comment by chentingpc** [comment]
are you running on TPU? and did you set the FLAG `use_tpu=False`?

**Comment by Ivy-C-85** [comment]
I'm running on GPU and set the FLAG False. I've already solved this, still
used the method changing the to 'SLICE' to 'V1'. Thanks!
